
import { InventoryItem, Catalog } from './types';

export const DEFAULT_SHEET_URL = "https://script.google.com/macros/s/AKfycbwrXpGbk2hqkQqGcYxnJgPqjjYCQB32kTSGQCIIyHu386o91wMhx8xcOIazXkuMuk8/exec";

export const INITIAL_INVENTORY: InventoryItem[] = [];

export const CATALOG: Catalog = {
  PROVEEDOR: ["1&1", "Adobe", "Amazon", "Arquímedes", "Autodesk", "BackMarket", "Carrefour", "Construbit", "CYPE", "Digital River", "EcoPC", "ElasticEmail", "ElCorteIngles", "Fairphone", "Fleet", "GoDaddy", "GSuite", "Heroku", "Honesting", "Humhub", "Iscarnet", "Join.me", "Linkedin", "Localizador Sherlog", "Mailchimp", "MediaMarkt", "Nuki Home", "O2online", "Ocasionia", "Office", "Orange", "Passpack", "PC Expansión", "PCComponentes", "PluralSight", "SegundamanoPC", "Scaleway", "Slack", "Typeform", "Unbounce", "Upviral", "VNet", "Zoho"],
  EMPRESA: ["Alteina", "CoCircular", "Devera (Eco Impact Tech)", "Fundacion Felisa", "Fundacion SocialNest", "Gonido (Build Tech Energy)", "Greenest AI", "Griffo Solutions", "Hands-on Impact", "Ikosia Energy Solutions", "iPoble (Zubi New Ventures)", "Kampe (Learning on the Job)", "Matteco (Matteco Team)", "Mosaik Systems (ZCi)", "Nebula (Zubi New Ventures)", "Onerz (Zubi Labs Impact)", "Parque Felisa", "Seal Hydrogen", "Sustainable Towns (ZCi)", "Teradx Diagnostics", "Trebe Desarrollos (ZCi)", "Trobatea (Zubi Labs Impact)", "Woodea", "Zeronet IT Efficient", "Zubi Capital", "Zubi Cities", "Zubi Education", "Zubi Family", "Zubi Group Impact", "Zubi Labs Impact", "Zubi New Ventures", "Zubi Wealth Management"],
  TIPO: ["AC_Accesorios", "AD_Adaptador", "AN_Antena", "AP_AccesPoint", "AR_Acc-Remoto", "AV_Altavoces", "CA_Cables-Audio", "CB_ChromeBook", "CH_Cables-HDMI", "CM_Camara-Vig", "CV_Capturadora", "DK_Dock", "HS_Auriculares", "KB_Keyboard", "LD_Lector-DNI", "MD_MandoTV", "MF_Microfono", "MN_Monitor", "MP_MousePad", "MS_Mouse", "MV_Móvil", "OG_OcolusGo", "PC_MiniPC", "PD_PenDrive", "PR_Impresora", "PT_Portatil", "RT_Router", "SC_SimCard", "SW_Software", "TB_Tablet", "TR_Combo", "TV_Television", "WC_Webcam"],
  DISPOSITIVO: ["Acc_Remoto", "Acces_Point", "Accesorios", "Adaptador", "Altavoces", "Antena", "Auriculares", "Cables_Audio", "Cables_HDMI", "Capturadora", "ChromeBook", "Combo", "Dock", "Gafas_RV", "Impresora", "Keyboard", "Lector_DNI", "Linea ILIMITADA", "Linea INFINITA", "Linea TARIFA PLANA", "Mando_TV", "Microfono", "MiniPC", "Monitor", "Mouse", "MousePad", "Movil Basico", "Movil Leasing", "Movil Premium", "Pendrive", "Portatil Basico", "Portatil Leasing", "Portatil Leasing+", "Portatil Medio", "Portatil Premium", "Portatil Premium+", "Router", "SecurityCam", "Software", "Tablet", "Television", "WebCam"],
  UBICACION: ["A Coruña", "Albalat de la Ribera", "Algemesi", "Alicante", "Arenys de Mar", "Barcelona", "Burjassot", "Cádiz", "Castellon", "El Puig", "Gandia", "Granada", "Grecia", "Imagine", "Islas Baleares", "Lanzarote", "La Pinada Fun", "La Pinada Lab", "Lleida", "Lliria", "Madrid", "Malaga", "Matteco", "Merida", "Mislata", "Moncofa", "Murcia", "Pamplona", "Paterna", "Pontevedra", "Rocafort", "Santa Coloma", "Santa Fe", "Sevilla", "Terminal Hub", "Valencia", "Valsain", "Zamora", "Zaragoza", "ZC_Madrid"],
  PROPIEDAD: ["CoCircular", "Devera", "Gonido", "Fundacion Felisa", "Greenest AI", "Hands-on Impact", "Matteco Team", "Medita", "Mosaik Systems", "Parque Felisa", "Personal", "Sustainable Towns", "Trebe Desarrollos", "Woodea", "Zeronet IT Efficient", "Zubi Capital", "Zubi Cities", "Zubi Education", "Zubi Group Impact", "Zubi Labs Impact", "Zubi New Ventures"],
  CIF_EMPRESA: ["B01617414", "B44834653", "G72609266", "B10684967", "B16910259", "B01787407", "B10663201", "B01857846", "B56263155", "B70771092", "nobody", "B98865892", "B01787381", "B10728590", "B75489310", "A40657306", "B98793409", "B98628100", "B40578270"],
  ESTADO: ["Alta", "Baja", "Bloqueo", "Extraviado", "Devolucion", "Indefinido", "Leasing", "Licencia", "Obsoleto", "Peticion", "Prestado", "Propiedad", "Reserva", "Suspendida", "Vendido"],
  MATERIAL: ["Entregado", "Obsoleto", "Revision", "Retornado", "Pendiente", "Vigente", "Propio", "Devuelto"],
  COMPAÑIA: ["Nunsys", "O2online", "Orange", "Pepephone"],
  CREADO_POR: ["AitorCarricondo", "vicsaez", "Trello", "jesusrivera", "eduardo_moreno", "vicente_saez"],
  BYOD: ["SÍ", "NO"]
};
